### ISSUE TITLE
your demo have Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by cctamlulu** [blippy/cerbo#1]
https://github.com/blippy/cerbo/blob/0ba4cc5de28f53d515026d85c18d5ba42bc40a7b/c/pss.c
Your should use `proc_info = readproc(proc, NULL)`

**Comment by cctamlulu** [comment]
For search
#include <proc/readproc.h>
libprocps

**Comment by blippy** [comment]
I don't quite follow. Are you saying the code should read:
`
int main(int argc, char** argv) {
  PROCTAB* proc = openproc(PROC_FILLMEM | PROC_FILLSTAT | PROC_FILLSTATUS);
  proc_t proc_info = = readproc(proc, NULL);
  while (readproc(proc, &proc_info)) {
    printf("%20s:\t%5ld\t%5lld\t%5lld\n",
           proc_info.cmd, proc_info.resident,
           proc_info.utime, proc_info.stime);
  }
  closeproc(proc);
}
`

**Comment by blippy** [comment]
Closed, as no code had been given.

**Comment by cctamlulu** [comment]
I mean that :
```
int main(int argc, char** argv) {
  PROCTAB* proc = openproc(PROC_FILLMEM | PROC_FILLSTAT | PROC_FILLSTATUS);
  proc_t* proc_info;
  while ((proc_info = readproc(proc, NULL)) != NULL){
  	// ...
  }
  closeproc(proc);
}
```

**Comment by blippy** [comment]
Thanks for that. Change made as suggested.

**Comment by cctamlulu** [comment]
Thanks for your demo.
It may be help somebody out.
